version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  # Postgres DBs for isolation (different ports exported for local DB access)
  user_db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: userdb
    ports: ["5433:5432"]

  product_db:
    image: postgres:16
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: productpass
      POSTGRES_DB: productdb
    ports: ["5434:5432"]

  order_db:
    image: postgres:16
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: orderpass
      POSTGRES_DB: orderdb
    ports: ["5435:5432"]

  # Services
  user_service:
    build: ./user_service
    env_file: ./user_service/.env
    depends_on: [user_db, redis]
    ports: ["8001:8000"]

  product_service:
    build: ./product_service
    env_file: ./product_service/.env
    depends_on: [product_db, redis]
    ports: ["8002:8000"]
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: productpass
      POSTGRES_DB: productdb
      POSTGRES_HOST: product_db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  order_service:
    build: ./order_service
    env_file: ./order_service/.env
    depends_on: [order_db, product_service, user_service, redis]
    ports: ["8003:8000"]
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: orderpass
      POSTGRES_DB: orderdb
      POSTGRES_HOST: order_db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PRODUCT_SERVICE_URL: "http://product_service:8000"
      USER_SERVICE_URL: "http://user_service:8000"

  notification_service:
    build: ./notification_service
    depends_on: [redis]

  gateway:
    build: ./gateway
    container_name: gateway
    env_file: ./gateway/.env
    depends_on: [user_service,product_service,order_service]
    ports: ["8000:8000"]
    environment:
      USER_SERVICE_URL: "http://user_service:8000"
      PRODUCT_SERVICE_URL: "http://product_service:8000"
      ORDER_SERVICE_URL: "http://order_service:8000"

